# Generated by Django 5.0.2 on 2024-02-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
