# Generated by Django 5.0.2 on 2024-02-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_user_alter_recipes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.IntegerField(),
        ),
    ]
